name: Upsert record

on: [repository_dispatch]

jobs:
  upsert:
    if: github.event.action == 'upsert'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Upsert record
        uses: jwulf/ghettohubDB@master
        with:
          operation: UPSERT
          github_token: ${{ secrets.GITHUB_TOKEN }}
          record: '{"name": "Joe Bloggs", "address": "The Dog House"}'
          table: customers
      
